### PR TITLE
Remove /debian directory from the project

### PR DESCRIPTION
**Pull request by bobek**
Hi Joachim,

I would like to propose removal of debian related stuff. I have created a new repo under https://github.com/bobek/pkg-pimd to simplify Debian related work flow with git-buildpackage.

What do you think?

Thanks,

   Antonin

### CODE REVIEW

**Comment by troglobit** [comment]
Sure, no problem, if it makes life easier for Debian I'm all for it! :)

However, I think I'd like to see a reference to https://github.com/bobek/pkg-pimd somewhere in the project. I'll think about it, I guess for now I'll make do with the ChangeLog.

Btw, I'll do a minor v2.3.1 bugfix release any day now ... in case you're planning a new Debian release.  So anything you want fixed for that can go into master now.

**Comment by bobek** [comment]
Awesome, thank you. I had those typos only for now as the actual 2.3.0 release is fixing a bunch of problems reported on Debian side as well. I am planning to push it asap. But no problem in following up with 2.3.1.

BTW Awesome news, Apollon (https://qa.debian.org/developer.php?login=apoikos@debian.org / @apoikos ) contacted me with an offer for co-maintanance of the package. Which I had gladly accepted. He is using pimd in production in his day job, so he can dedicate quite some time into maintenance of the package. Which is awesome news as my day job (http://www.showmax.com) doesn't allow me to do so very frequently.

**Comment by troglobit** [comment]
Alright, then I take it there's no rush to get v2.3.1 released and I postpone the release work to this coming weekend? :+1: 

That is truly awesome news, glad to hear! :smiley:

**Comment by apoikos** [comment]
Hi!

@bobek, we could also consider hosting the repository on alioth (under 
collab-maint for example).

@troglobit, thanks a lot for taking care of pimd :)

Cheers,
Apollon

**Comment by bobek** [comment]
@apoikos, I've actually started with that. But repository creation was a bit broken yesterday, so I gave up and went for github.

**Comment by troglobit** [comment]
@bobek @apoikos Unless you've not seen it, I've released [v2.3.1](https://github.com/troglobit/pimd/releases/tag/2.3.1) now.

Cheers

**Comment by bobek** [comment]
@troglobit awesome, I've pushed new version to Debian. Thanks for heads up.

**Pull request merged**
